
* Performance and Design
** What is Performance?
** Do you know your implementations performance?
** Do you know your hardware?
*** links
**** Sandy Bridge CPU layout
http://arstechnica.com/business/2010/09/intels-next-must-have-upgrade-a-look-at-sandy-bridge/
**** STARTED Ivy bridge CPU layout
http://arstechnica.com/business/2012/04/intels-tick-plus-third-generation-core-ivy-bridge-processors-hit-the-market/
**** STARTED Haswell bridge CPU layout
http://arstechnica.com/gadgets/2013/05/a-look-at-haswell/
** The case of the calibration
*** sum on very large arrays
**** TODO look-up number of cells of ATLAS calo
**** TODO use LogNormal or Normal-Distribution in 3D to do some scaling/calibration
***** 1/(r sigma sqrt(2*pi))exp((ln (r) - mu)^2/(2*sigma*sigma))
***** 1/(sigma sqrt(2*pi))exp((r - mu)^2/(2*sigma*sigma))
****** log/exp can only be emulated with SIMD
***** pol5 fit to 15k samples of normal PDF
****** fit results
***************************************
Minimizer is Linear
Chi2                      =      32.2417
NDf                       =           34
p0                        =      1225.51   +/-   26.2991     
p1                        =     -50.2466   +/-   84.9579     
p2                        =     -844.775   +/-   90.2873     
p3                        =      467.178   +/-   41.5544     
p4                        =     -95.9609   +/-   8.68852     
p5                        =       6.9906   +/-   0.678148
****** only use up to x<4.
**** TODO provide benchmarks
***** naive C style
***** design = 1 Cell = 1 Object
*** SIMD
**** intro SIMD
**** is model of performance possible
*** Multi-threading
**** numa-effects
**** blocking
** architecture = C style
** optimise only what needs optimisation

* CRTP and Expression Templates
** TODO rewrite all code in terms of calibration example?

* Test-Driven ?
